apiVersion: trusted-images.bocklabs.dev/v1
kind: Image
metadata:
  name: open-webui-qualification
spec:
  upstream:
    ref: ghcr.io/open-webui/open-webui
    tag: v0.11.4
    digest: sha256:9591b13f13843c7721c2b8eaf7382846c81b3ffe126526d1888d1fed50c6a33f
  destination:
    package: ghcr.io/bocklabs/open-webui-qualification
  patchPolicy: enabled
  validation:
    type: http
    port: 8080
    path: /health
    durationSeconds: 180
  version: 2
