apiVersion: trusted-images.bocklabs.dev/v1
kind: Image
metadata:
  name: ollama
spec:
  upstream:
    ref: docker.io/ollama/ollama
    tag: 0.40.0-rc0-rocm
    digest: sha256:215f960591137e844e17b5f735fb877b9e4f022322bcc22aeb8574f5fe0ecf08
  destination:
    package: ghcr.io/bocklabs/ollama
  patchPolicy: enabled
  validation:
    type: http
    port: 11434
    path: /api/version
  version: 2
