apiVersion: trusted-images.bocklabs.dev/v1
kind: Image
metadata:
  name: ollama
spec:
  upstream:
    ref: docker.io/ollama/ollama
    tag: 0.40.0
    digest: sha256:1bef639749741b375e9a1eb2c1346fb57ce52f5432de1f74846e44ccc18e1687
  destination:
    package: ghcr.io/bocklabs/ollama
  patchPolicy: enabled
  validation:
    type: http
    port: 11434
    path: /api/version
  version: 2
